name: Trigger Netlify Build
on:
  schedule:
    - cron: '*/5 * * * *'
#    - cron: '0 */1 * * *'
jobs:
  build:
    name: Request Netlify Webhook
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        run: curl -X POST -d {} https://api.netlify.com/build_hooks/5eedcb158ae8d034dbe3c00c
